import type { Project } from "@/types";
import { buildResolvedStructure } from "./exportZip";
import { slugify } from "@/utils/helpers";

/* ============================================================
   Standalone project generator — turns a ProjectConfig into a
   complete, runnable React/Vite client website.

   The generated project reuses the SAME website layer the studio
   preview renders (embedded from the build-time source catalogue),
   so what the client receives is byte-identical to the preview.
   ============================================================ */

export type SourceCatalogue = Record<string, string>;

/** Strip tailwind studio chrome — the website layer only needs tokens + utilities */
const GENERATED_INDEX_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

/* Theme tokens for the generated client site */
:root {
  --ks-bg: #0d100c;
  --ks-surface-0: #0d100c;
  --ks-surface-1: #131712;
  --ks-surface-2: #191d17;
  --ks-surface-3: #20251d;
  --ks-ink: #f0f4ea;
  --ks-ink-muted: #a3ad9d;
  --ks-ink-faint: #68725f;
  --ks-line: rgba(238, 244, 229, 0.08);
  --ks-line-strong: rgba(238, 244, 229, 0.14);
  --ks-accent: #d7ff4f;
  --ks-accent-hover: #e4ff83;
  --ks-accent-ink: #151a05;
  --ks-brand: #d7ff4f;
  --ks-brand-hover: #e4ff83;
  --ks-brand-muted: rgba(215, 255, 79, 0.1);
  --ks-brand-ring: rgba(215, 255, 79, 0.42);
  --ks-surface-0-rgb: 13 16 12;
  --ks-surface-1-rgb: 19 23 18;
  --ks-surface-2-rgb: 25 29 23;
  --ks-surface-3-rgb: 32 37 29;
  --ks-ink-rgb: 240 244 234;
  --ks-ink-muted-rgb: 163 173 157;
  --ks-ink-faint-rgb: 104 114 95;
  --ks-brand-rgb: 215 255 79;
  --ks-brand-hover-rgb: 228 255 131;
  color-scheme: dark;
}

html, body, #root { height: 100%; }
body {
  margin: 0;
  background: #0d100c;
  color: #f0f4ea;
  font-family: "Inter", ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
  -webkit-font-smoothing: antialiased;
}
`;

const GENERATED_APP_TSX = `/* AUTO-GENERATED by Katch Studio — the standalone client website.
   Renders the exact website layer used by the studio preview. */
import WebsiteRenderer from "@/website/WebsiteRenderer";
import type { ProjectConfig, SectionInstance } from "@/types";
import website from "@/data/website.json";

function buildConfig(data: any): ProjectConfig {
  const sections: SectionInstance[] = [];
  const pages = (data.pages ?? []).map((p: any) => ({
    id: p.id,
    name: p.name,
    path: p.path,
    seo: p.seo ?? { title: "", description: "", keywords: "", ogImage: "", index: true },
    sections: (p.sections ?? []).map((s: any) => {
      sections.push({
        id: s.id,
        type: s.type,
        hidden: s.hidden ?? false,
        variant: s.variant,
        styles: s.styles,
        content: s.content ?? {},
      });
      return s.id;
    }),
  }));

  return {
    projectInfo: {
      name: data.project?.name ?? "Website",
      client: data.project?.client ?? "",
      category: data.project?.category ?? "business",
      description: "",
      audience: "",
      language: data.project?.language ?? "en",
    },
    brand: data.brand ?? { businessName: "Your Brand", logoText: "Your Brand", logoFormat: "wordmark" },
    theme: data.theme ?? {},
    pages,
    sections,
    features: Object.entries(data.features ?? {}).map(([id, f]: [string, any]) => ({
      id,
      enabled: f?.enabled ?? true,
    })),
    templateId: "",
  };
}

export default function App() {
  return <WebsiteRenderer project={buildConfig(website)} />;
}
`;

const GENERATED_MAIN_TSX = `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;

const GENERATED_TYPES_INDEX = `export * from "./theme";
export * from "./sections";
export * from "./project";
`;

const GENERATED_VITE_CONFIG = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath, URL } from "node:url";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) },
  },
});
`;

const GENERATED_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"] }
  },
  "include": ["src"]
}
`;

const GENERATED_POSTCSS = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

const TAILWIND_CONFIG = `import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: {
          0: "rgb(var(--ks-surface-0-rgb) / <alpha-value>)",
          1: "rgb(var(--ks-surface-1-rgb) / <alpha-value>)",
          2: "rgb(var(--ks-surface-2-rgb) / <alpha-value>)",
          3: "rgb(var(--ks-surface-3-rgb) / <alpha-value>)",
        },
        ink: {
          DEFAULT: "rgb(var(--ks-ink-rgb) / <alpha-value>)",
          muted: "rgb(var(--ks-ink-muted-rgb) / <alpha-value>)",
          faint: "rgb(var(--ks-ink-faint-rgb) / <alpha-value>)",
        },
        line: {
          DEFAULT: "var(--ks-line)",
          strong: "var(--ks-line-strong)",
        },
        brand: {
          DEFAULT: "rgb(var(--ks-brand-rgb) / <alpha-value>)",
          hover: "rgb(var(--ks-brand-hover-rgb) / <alpha-value>)",
          muted: "var(--ks-brand-muted)",
          ring: "var(--ks-brand-ring)",
        },
        accent: {
          DEFAULT: "rgb(var(--ks-brand-rgb) / <alpha-value>)",
          muted: "var(--ks-brand-muted)",
        },
        katch: {
          DEFAULT: "var(--ks-accent)",
          hover: "var(--ks-accent-hover)",
          ink: "var(--ks-accent-ink)",
        },
        ok: "#34d399",
        warn: "#fbbf24",
        danger: { DEFAULT: "#f87171", muted: "rgba(248,113,113,0.12)" },
        info: "#60a5fa",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "Segoe UI", "sans-serif"],
        display: ["Sora", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
`;

const GENERATED_INDEX_HTML = (title: string) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${title.replace(/"/g, "&quot;")}" />
    <title>${title.replace(/"/g, "&quot;")}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

const GENERATED_PACKAGE = (name: string) => JSON.stringify(
  {
    name,
    private: true,
    version: "1.0.0",
    type: "module",
    scripts: { dev: "vite", build: "tsc --noEmit && vite build", preview: "vite preview" },
    dependencies: {
      "lucide-react": "^0.441.0",
      react: "^18.3.1",
      "react-dom": "^18.3.1",
    },
    devDependencies: {
      "@types/react": "^18.3.8",
      "@types/react-dom": "^18.3.0",
      "@vitejs/plugin-react": "^4.6.0",
      autoprefixer: "^10.4.20",
      postcss: "^8.4.47",
      tailwindcss: "^3.4.12",
      typescript: "^5.6.2",
      vite: "^6.4.3",
    },
  },
  null,
  2
);

/* ---------- Image embedding (browser) ---------- */

const MAX_EMBED_BYTES = 1_500_000;

async function toDataUrl(url: string): Promise<string> {
  const res = await fetch(url, { mode: "cors" });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const blob = await res.blob();
  if (blob.size > MAX_EMBED_BYTES) throw new Error("too large");
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(new Error("read failed"));
    reader.readAsDataURL(blob);
  });
}

/** Resolve image URLs (studio asset paths / external URLs) into data URIs so
 *  the exported project is fully self-contained. Failures keep the URL. */
export async function embedImages<T>(value: T, origin: string): Promise<T> {
  if (typeof value === "string") {
    const isData = value.startsWith("data:");
    const isLocal = value.startsWith("/") && !value.startsWith("//");
    const isHttp = value.startsWith("http://") || value.startsWith("https://");
    if (isData) return value as unknown as T;
    if (isLocal) {
      try {
        return (await toDataUrl(origin + value)) as unknown as T;
      } catch {
        return value as unknown as T;
      }
    }
    if (isHttp) {
      /* Same-origin asset URLs get embedded; external URLs are left alone
         (cross-origin fetching usually fails and that's fine). */
      try {
        if (new URL(value).origin === origin) return (await toDataUrl(value)) as unknown as T;
      } catch {
        /* invalid URL — leave as-is */
      }
      return value as unknown as T;
    }
    return value as unknown as T;
  }
  if (Array.isArray(value)) {
    const out: unknown[] = [];
    for (const item of value) out.push(await embedImages(item, origin));
    return out as unknown as T;
  }
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = await embedImages(v, origin);
    }
    return out as unknown as T;
  }
  return value;
}

/* ---------- File assembly ---------- */

export interface ScaffoldOptions {
  /** Embed studio/local images as data URIs (browser). Node tests pass false. */
  embed?: boolean;
  origin?: string;
}

/** Assemble the complete standalone project file map. */
export async function buildScaffoldFiles(
  project: Project,
  catalogue: SourceCatalogue,
  options: ScaffoldOptions = {}
): Promise<Record<string, string>> {
  let structure = buildResolvedStructure(project);
  if (options.embed) {
    const origin = options.origin ?? window.location.origin;
    structure = await embedImages(structure, origin);
  }

  const slug = slugify(project.config.projectInfo.name || "client-project") || "client-project";
  const title = project.config.projectInfo.name || "Client Website";
  const brand = project.config.brand;

  const files: Record<string, string> = {};

  /* The real website layer — verbatim from the build-time catalogue */
  for (const [path, content] of Object.entries(catalogue)) {
    files[path] = content;
  }

  files["package.json"] = GENERATED_PACKAGE(slug);
  files["tsconfig.json"] = GENERATED_TSCONFIG;
  files["vite.config.ts"] = GENERATED_VITE_CONFIG;
  files["tailwind.config.ts"] = TAILWIND_CONFIG;
  files["postcss.config.js"] = GENERATED_POSTCSS;
  files["index.html"] = GENERATED_INDEX_HTML(title);
  files["src/index.css"] = GENERATED_INDEX_CSS;
  files["src/main.tsx"] = GENERATED_MAIN_TSX;
  files["src/App.tsx"] = GENERATED_APP_TSX;
  files["src/types/index.ts"] = GENERATED_TYPES_INDEX;
  files["src/data/website.json"] = JSON.stringify(structure, null, 2);
  files["README.md"] = [
    `# ${title}`,
    "",
    `> Generated by **Katch Studio** on ${new Date().toLocaleString()}.`,
    "",
    "A standalone React/Vite website rendered by the same engine as the studio preview.",
    "",
    "## Quick start",
    "",
    "```bash",
    "npm install",
    "npm run dev      # local development",
    "npm run build    # production build → dist/",
    "```",
    "",
    "## Where the content lives",
    "",
    "- `src/data/website.json` — every page, section, image, color and text of the site",
    "- `src/website/` — the reusable section components",
    "- `src/types/` — the configuration data model",
    "",
    "## Making changes",
    "",
    "Edit values in `src/data/website.json` (titles, buttons, prices, images…), or change",
    "the site's colors/typography under `theme` — everything re-renders. For structural",
    "changes, sections can be added/removed/reordered per page in the `pages` array.",
    "",
    `Client: ${project.config.projectInfo.client || "—"}`,
    `Website type: ${project.config.projectInfo.category}`,
    `Language: ${project.config.projectInfo.language === "ar" ? "Arabic (RTL)" : "English (LTR)"}`,
    `Brand: ${brand.businessName || "—"}`,
  ].join("\n");

  return files;
}

/* ---------- ZIP (browser) ---------- */

export async function buildScaffoldZip(
  project: Project,
  catalogue: SourceCatalogue,
  options: ScaffoldOptions = {}
): Promise<Blob> {
  const JSZip = (await import("jszip")).default;
  const zip = new JSZip();
  const files = await buildScaffoldFiles(project, catalogue, options);
  const slug = slugify(project.config.projectInfo.name || "client-project") || "client-project";
  for (const [path, content] of Object.entries(files)) {
    zip.file(`${slug}/${path}`, content);
  }
  return zip.generateAsync({ type: "blob" });
}

export function scaffoldZipFilename(project: Project): string {
  const slug = slugify(project.config.projectInfo.name || "project") || "project";
  return `katch-site-${slug}.zip`;
}
