/* scaffold-verify — generates a standalone project from the Looky Cakes
   demo, writes it to a temp folder, then the caller runs
   `npm install && npm run build` inside it to prove it compiles.
   Usage: node scripts/scaffold-verify.mjs */
import { build } from "esbuild";
import { pathToFileURL } from "node:url";
import { mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import path from "node:path";

const OUT = "/tmp/ks-scaffold";
rmSync(OUT, { recursive: true, force: true });

/* 1. Bundle a tiny entry exporting the demo projects + scaffold builder */
await build({
  entryPoints: ["scripts/scaffold-entry.ts"],
  bundle: true,
  platform: "node",
  format: "esm",
  outfile: "/tmp/ks-scaffold-bundle.mjs",
  alias: { "@": "./src" },
  loader: { ".jpg": "dataurl", ".png": "dataurl" },
  logLevel: "silent",
  target: "es2020",
});

/* 2. Load the catalogue (generated by scripts/generate-catalogue.mjs) */
const catalogue = JSON.parse(readFileSync(path.join(process.cwd(), "src/features/export/catalogue.json"), "utf8"));

/* 3. Generate */
const { buildDemoProjects } = await import(pathToFileURL("/tmp/ks-scaffold-bundle.mjs").href + "?scaffold");
const { buildScaffoldFiles } = await import(pathToFileURL("/tmp/ks-scaffold-bundle.mjs").href + "?scaffold2");
const looky = buildDemoProjects().find((p) => p.config.projectInfo.name === "Looky Cakes");
const files = await buildScaffoldFiles(looky, catalogue, { embed: false });

for (const [file, content] of Object.entries(files)) {
  const abs = path.join(OUT, file);
  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, content);
}
console.log(`✓ Generated ${Object.keys(files).length} files in ${OUT}`);
console.log("  Next: cd /tmp/ks-scaffold && npm install && npm run build");
