/* ============================================================
   Repository name normalization — shared rules for valid GitHub
   repository names, mirroring the client-side helper
   (src/features/deploy/naming.ts). Server-side this is a
   SECURITY control: the client's name is validated here too.

   "Looky Cakes"  → katch-looky-cakes
   "حلويات"       → katch-site        (no latin letters → fallback)
   "Bta3 7awa4y"  → katch-bta3-7awa4y
   ============================================================ */

const REPO_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** Normalize a project name into a GitHub-safe repository name. */
export function normalizeRepoName(name, fallbackId = "") {
  const latin = String(name ?? "")
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents
    .replace(/[^a-z0-9\s-]/g, "") // letters/digits/spaces/hyphens only (drops Arabic etc.)
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/^(katch-)+/, ""); // avoid katch-katch-…
  const base = latin || "site";
  /* Only fall back to the project id when there are NO usable letters
     (e.g. Arabic-only names) — normal names stay clean ("katch-looky-cakes"). */
  const suffix =
    !latin && fallbackId
      ? `-${String(fallbackId).toLowerCase().replace(/[^a-z0-9]/g, "").slice(0, 6)}`
      : "";
  return `katch-${base}${suffix}`.slice(0, 100).replace(/-+$/g, "") || "katch-site";
}

/** Hard validation of a repository name (used server-side on every request). */
export function isValidRepoName(name) {
  return typeof name === "string" && name.length > 0 && name.length <= 100 && REPO_PATTERN.test(name);
}

/** Marker stored in the repo description so a redeploy can recognise
 *  the repository that belongs to THIS project (duplicate handling). */
export function repoMarker(projectId) {
  return `Generated by Katch Studio · project ${projectId}`;
}

export function repoMatchesMarker(description, projectId) {
  return typeof description === "string" && description.includes(`project ${projectId}`);
}
